### PR TITLE
Adding code to run on Powersystem

### PR DESCRIPTION
**Pull request by genisysram**
Hi
Here is my contribution to your code, its working good on powersystems.

Thanks for the code, its working good.
## What do these changes do?
Added Architecture "ppc64le"
## Are there changes in behavior for the user?
No

### CODE REVIEW

**Comment by waddlesplash** [comment]
This file only affects CI builds; is the change really needed?

**Comment by genisysram** [comment]
Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing

**Comment by genisysram** [comment]
@waddlesplash
Please merge my PR

**Comment by waddlesplash** [comment]
I don't know that we care to spend the time to ensure PPC builds always work, it seems like a pretty niche usecase. We will accept patches to fix PPC if it breaks, but I don't think we care to ensure it does not.

**Comment by genisysram** [comment]
If there is break in code in near feauture ,@Siddhesh-Ghadi will fix if it get escalated to his notice .
Now , merge the PR

**Pull request closed without merging**
